### ISSUE TITLE
Type problem

### ISSUE THREAD

**Issue by dmnbi4** [russtone/homebridge-mi-humidifier#12]
После обновления homebridge на версию 0.4.47  вылетает следующая ошибка:

```
throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^
Error: The requested accessory 'MiHumidifier' was not registered by any plugin.
at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:296:42)
at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:38)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:701:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
at Module.load (internal/modules/cjs/loader.js:600:32)
at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

Конфиг я не менял:

```
   "accessories": [
        {
            "accessory": "MiHumidifier",
            "name": "Увлажнитель",
            "ip": "192.168.88.227",
            "token": "xxxxxxxxxxx",
            "model": "v1",
            "showTemperature": true,
          "nameTemperature": "Температура увлажнителя"
        }
    ],
```

**Comment by russtone** [comment]
I've updated homebridge to 0.4.47 and it seems that plugin works fine for me.
Are you sure that you installed `homebridge-mi-humidifier` globally (with `-g` option)?

**Comment by dmnbi4** [comment]
Not globally because i use docker.

**Comment by f0rtis** [comment]
The issue still exists. I've installed the plugin using Homebridge web interface. I don't know whether Homebridge installs the plugin globally or not, but it has to work, as non-experienced users can't make it work.

**Comment by f0rtis** [comment]
@russtone I saw you moved "miio": "^0.15.6" to dependencies instead of engines. It helped! Thank you!

**Comment by russtone** [comment]
@f0rtis Yes, I've fixed the issue and was going to write a comment)
