### ISSUE TITLE
 Add support for deerma.humidifier.jsq1

### ISSUE THREAD

**Issue by shenmirenQUQ** [russtone/homebridge-mi-humidifier#38]
Thanks for the plugin。
Wonder if you could have a plan on updating the plugin to work with this model? 
`it's new mi humidifier, miio model deerma.humidifier.jsq1
[https://www.xiaomiyoupin.com/detail?gid=127259&spmref=YouPinPC.$SearchFilter$1.search_list.2.20959750](url)
Thank you and looking forward to seeing your reply.

**Comment by shenmirenQUQ** [comment]
[9/23/2020, 11:07:29 PM] [Humidifier] getTargetRelativeHumidity Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}

**Comment by shenmirenQUQ** [comment]
[9/23/2020, 11:10:59 PM] [Humidifier] getCurrentHumidifierState Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:03 PM] [Humidifier] getActive Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:04 PM] [Humidifier] getTargetRelativeHumidity Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:05 PM] [Humidifier] getCurrentRelativeHumidity Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:07 PM] [Humidifier] getMute Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:07 PM] [Humidifier] getWaterLevel Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:08 PM] [Humidifier] getSwitch1 Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:09 PM] [Humidifier] getRotationSpeed Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:09 PM] [Humidifier] getSwitch1 Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:09 PM] [Humidifier] getRotationSpeed Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:09 PM] [Humidifier] getCurrentRelativeHumidity Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:10 PM] [Humidifier] getCurrentRelativeHumidity Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:10 PM] [Humidifier] getWaterLevel Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:10 PM] [Humidifier] getCurrentHumidifierState Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:10 PM] [Humidifier] getActive Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:11 PM] [Humidifier] getWaterLevel Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:11 PM] [Humidifier] getCurrentHumidifierState Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:11 PM] [Humidifier] getCurrentTemperature Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:11 PM] [Humidifier] getActive Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:11 PM] [Humidifier] getCurrentTemperature Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:11 PM] [Humidifier] getCurrentRelativeHumidity Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:11 PM] [Humidifier] getRotationSpeed Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}
[9/23/2020, 11:11:12 PM] [Humidifier] getMute Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8) {
  code: -30012
}

**Comment by shenmirenQUQ** [comment]
https://github.com/rytilahti/python-miio/blob/master/miio/airhumidifier_jsq.py

**Comment by nikitafedorovv** [comment]
+1

**Comment by titanzx** [comment]
+1

**Comment by russtone** [comment]
Model `deerma.humidifier.jsq1` is supported by the new version of the plugin, so I am closing this.
