### ISSUE TITLE
The requested accessory 'MiHumidifier' was not registered by any plugin after updating to 1.4.0

### ISSUE THREAD

**Issue by mrdc** [russtone/homebridge-mi-humidifier#40]
Hello, 

I'm using Homebridge Docker image from oznu. After updating the plugin to version 1.4.0 Homebridge fails on boot with this error:
`The requested accessory 'MiHumidifier' was not registered by any plugin`

**Homebridge Log:**
```
[10/11/2020, 9:02:09 PM] ERROR LOADING PLUGIN homebridge-mi-humidifier:,
[10/11/2020, 9:02:09 PM] /homebridge/node_modules/homebridge-mi-humidifier/devices/MiHumidifierFactory.js:5,
  static adapterVersionMap = {,
                           ^,
SyntaxError: Unexpected token =,
    at Module._compile (internal/modules/cjs/loader.js:723:23),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),
    at Module.load (internal/modules/cjs/loader.js:653:32),
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12),
    at Function.Module._load (internal/modules/cjs/loader.js:585:3),
    at Module.require (internal/modules/cjs/loader.js:692:17),
    at require (internal/modules/cjs/helpers.js:25:18),
    at Object.<anonymous> (/homebridge/node_modules/homebridge-mi-humidifier/index.js:6:29),
    at Module._compile (internal/modules/cjs/loader.js:778:30),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),

[10/11/2020, 9:02:21 PM] Error: The requested accessory 'MiHumidifier' was not registered by any plugin.,
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13),
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42),
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38),
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10),
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22),
    at Module._compile (internal/modules/cjs/loader.js:778:30),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),
    at Module.load (internal/modules/cjs/loader.js:653:32),
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12),
    at Function.Module._load (internal/modules/cjs/loader.js:585:3),
```
**Homebridge config:**
```
    {
            "name": "Humidifier",
            "ip": "192.168.1.30",
            "token": "xxxxxxxxx",
            "model": "v1",
            "showTemperature": true,
            "nameTemperature": "Temperature",
            "showHumidity": true,
            "nameHumidity": "Humidity",
            "accessory": "MiHumidifier"
        }
```

**Comment by mrdc** [comment]
After installing the latest version of the plugin in regular Homebridge (not in Docker) everything works fine.
