### ISSUE TITLE
Update status error

### ISSUE THREAD

**Issue by netRunner0** [russtone/homebridge-mi-humidifier#5]
Thanks for the water level!

However, as with the previous version, that with this one, the following problems are observed for the humidifier version 2:

If you enter the home program, the homebridge device status update ends - the device does not respond] (along with the homebridge).
If you restart the program, then in most cases it disappears.
This manifests itself only when the plug-in for the humidifier is on.

Homebridge/miio update

**Comment by netRunner0** [comment]
Rebooted several times Raspberry, 
the following error occurred (only with one, the other works fine),

[2018-10-11 23:35:52] [Увлажнитель спальня] getCurrentTemperature TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getCurrentTemperature (/usr/lib/node_modules/homebridge-mi-humidifier/index.js:253:49)
    at emitThree (events.js:136:13)
    at Characteristic.CurrentTemperature.emit (events.js:217:7)
    at Characteristic.CurrentTemperature.Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:163:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:760:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:724:8)
    at emitMany (events.js:147:13)
    at HAPServer.emit (events.js:224:7)
    at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:926:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by pisikaki** [comment]
@netRunner0 It works with miio 0.14.1. 
npm install -g miio@0.14.1

**Comment by netRunner0** [comment]
Token error) Fixed!

**Comment by resure** [comment]
I'm getting the same error, even with miio 0.14.1: 

https://gist.github.com/resure/579b831823fd53d9ad42cc258a5bd84c

**Comment by russtone** [comment]
I can't reproduce this bug. I've added rediscover on failure (every 60s) in the latest version: https://github.com/russtone/homebridge-mi-humidifier/blob/3ddfa699fcae3920627980cd1bd8c018c2c52815/index.js#L114. Maybe it will help.

**Comment by JohanRus** [comment]
Hi.
Not work on Xiaomi Smartmi Pure Evaporative Air Humidifier (zhimi.humidifier.ca1).
miio v0.15.6 + homebridge v0.4.45 + homebridge-mi-humidifier v1.0.4
Also added a device to miio/lib/model.js ('zhimi.humidifier.ca1': Humidifier,)

[2018-11-26 22:45:01] [Bedroom Humidifier] Fail to discover the device. Retry in 1 minute { Error: Could not connect to device, handshake timeout
    at Timeout.handshakeTimeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/miio/lib/network.js:427:17)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) code: 'timeout', device: null }
[2018-11-26 22:45:17] [Bedroom Humidifier] getCurrentHumidifierState TypeError: Cannot read property 'call' of undefined
    at MiHumidifier.getCurrentHumidifierState (/usr/local/lib/node_modules/homebridge-mi-humidifier/index.js:154:43)
    at emitThree (events.js:136:13)
    at Characteristic.CurrentHumidifierDehumidifierState.emit (events.js:217:7)
    at Characteristic.CurrentHumidifierDehumidifierState.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:163:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:760:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:724:8)
    at emitMany (events.js:147:13)
    at HAPServer.emit (events.js:224:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:926:10)

**Comment by russtone** [comment]
It seems that in your case there is a problem with device discovering. Can you see your device in output of `miio discover` command?

**Comment by JohanRus** [comment]
**First start in pairing mode**

Device ID: 87256342
Model info: zhimi.humidifier.ca1
Address: 192.168.1.1
Token: 35……… via auto-token
Support: At least generic

**After creating a pair, the worker Wi-Fi**

Device ID: 87256342
Model info: Unknown
Address: 192.168.100.50
Token: ???
Support: Unknown

Token in the file ~/.local/share/miio is present

**Comment by JohanRus** [comment]
It works!
Miio in the setup mode of the humidifier(zhimi.humidifier.ca1) is not correctly receives a token. You need to use a token from the MiHome app after you set up the humidifier.

**Comment by rubbersoul935** [comment]
Hi!
Thank you for the plugin. It works great. 
But i have same problem as described here. 
Once uninstalled the plugin - accessories update immediately.
Pi 3 b+, Stretch.
Please do investigation.

**Comment by netRunner0** [comment]
This problem is solved.

https://github.com/aholstenson/miio/issues/192

**Comment by rubbersoul935** [comment]
Could you please explain what to do step by step, please?
Solution given in your link is hardly understandable.
This would be helpful for others. 
And in addition you might want to go to homebridge issues and help others giving link to the solution steps, that you will write here.

**Comment by netRunner0** [comment]
Just change to "zhimi.humidifier.ca1" from "zhimi.humidifier.v1" in the file @models.js in the folder with your plugin

**Comment by myxa27** [comment]
> Just change to "zhimi.humidifier.ca1" from "zhimi.humidifier.v1" in the file "models.js" in the folder with your plugin miio (etc /usr/lib/node_modules/miio/lib/models.js) and restart Homebridge

Hey. In version 1.0.5, this worked. After updating to version 1.1.0, problems with updating the status appeared again. Fix the problem please.
