### ISSUE TITLE
Invalid IP

### ISSUE THREAD

**Issue by jahnkenneth** [russtone/homebridge-mi-humidifier#52]
Hello,

I have a Mi Humidifier 2. I am getting the following error:

MiHumidifier] Invalid config for device #0}. Error: Ivalid IP address undefined
    at Object.validateConfig (/home/hoobs/.hoobs/node_modules/homebridge-mi-humidifier/dist/utils.js:18:15)
    at /home/hoobs/.hoobs/node_modules/homebridge-mi-humidifier/dist/platform.js:34:25
    at Array.forEach (<anonymous>)
    at MiHumidifierPlatform.didFinishLaunching (/home/hoobs/.hoobs/node_modules/homebridge-mi-humidifier/dist/platform.js:31:29)
    at HomebridgeAPI.emit (events.js:215:7)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:81:14)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:160:18)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

The IP-adress is correct...
My config:

[
    {
        "platform": "MiHumidifier",
        "devices": [
            {
                "name": "Luftfukter",
                "address": "192.168.68.194",
                "token": "2e563007425a05924d4e5eb6fb13daa0",
                "model": "zhimi.humidifier.ca4",
                "updateInterval": 30,
                "ledBulb": {
                    "enabled": true,
                    "name": "Humidifier LED"
                },
                "buzzerSwitch": {
                    "enabled": true,
                    "name": "Humidifier Buzzer"
                },
                "temperatureSensor": {
                    "enabled": true,
                    "name": "Humidifier Temperature"
                },
                "humiditySensor": {
                    "enabled": true,
                    "name": "Humidifier Humidity"
                }
            }
        ]
    }
]

**Comment by russtone** [comment]
Hey @jahnkenneth,
Is it content of "platforms" of your config?

**Comment by jahnkenneth** [comment]
Yes. I am using Hoobs.

Med hilsen,
Jahn Kenneth Juliussen

**Comment by russtone** [comment]
It seems that you use full homebridge config in field that requires to enter only config for specific device.
You configuration should be like this in Hoobs:

<img width="857" alt="iDB 2020-12-23 at 23 43 40" src="https://user-images.githubusercontent.com/3396041/103035734-fdb7b800-4578-11eb-8d3b-b4aeb53abe07.png">

**Comment by jahnkenneth** [comment]
Will try it.
Could you post it ad text, I can just copy and paste? :-)

**Comment by russtone** [comment]
```[
    {
        "name": "Luftfukter",
        "address": "192.168.68.194",
        "token": "2e563007425a05924d4e5eb6fb13daa0",
        "model": "zhimi.humidifier.ca4",
        "updateInterval": 30,
        "ledBulb": {
            "enabled": true,
            "name": "Humidifier LED"
        },
        "buzzerSwitch": {
            "enabled": true,
            "name": "Humidifier Buzzer"
        },
        "humiditySensor": {
            "enabled": true,
            "name": "Humidifier Temperature"
        },
        "temperatureSensor": {
            "enabled": true,
            "name": "Humidifier Humidity"
        }
    }
]```

**Comment by jahnkenneth** [comment]
23.12.2020, 22:11:32 [MiHumidifier] Fail to get props. SocketError: Timeout
    at /home/hoobs/.hoobs/node_modules/miio-api/dist/socket.js:106:39
    at done (/home/hoobs/.hoobs/node_modules/miio-api/dist/socket.js:92:13)
    at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/miio-api/dist/socket.js:106:21)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by jahnkenneth** [comment]
New error message.
The device shows up in Homekit, but no response from it...

**Comment by russtone** [comment]
Are you sure that IP and token are correct?

**Comment by DanoPlurana** [comment]
I ve got exactly the same problem. 

`[2/15/2021, 01:40:02] [MiHumidifier] [192.168.0.152] Fail to get device properties. SocketError: Timeout`

The IP and token are correct for sure. Any ideas?

**Comment by AyberkAltuntop** [comment]
I am having the same problem. I am sure the token and ip address are correct. 

<img width="1250" alt="Image" src="https://github.com/user-attachments/assets/d5ac4eeb-f583-4433-b75c-1385385d10f8" />

Can anyone solve the problem?

Thank you.
