### ISSUE TITLE
Invalid packet size, expected 176 got 32

### ISSUE THREAD

**Issue by coneybeare** [russtone/homebridge-mi-humidifier#66]
```
1/29/2021, 4:07:57 PM Error: Invalid packet size, expected 176 got 32
    at Function.fromBuffer (/home/hoobs/.hoobs/node_modules/miio-api/dist/packet.js:30:19)
    at socket.send.responseBuffer.responseBuffer (/home/hoobs/.hoobs/node_modules/miio-api/dist/device.js:148:57)
    at Socket.onMessage (/home/hoobs/.hoobs/node_modules/miio-api/dist/socket.js:101:32)
    at Socket.emit (events.js:314:20)
    at UDP.onMessage [as onmessage] (dgram.js:921:8)
1/29/2021, 4:07:57 PM Got SIGTERM, shutting down Bridge...
```

Setting up with

```
[
    {
      "name": "Humidifier",
      "address": "REDACTED",
      "token": "REDACTED",
      "model": "zhimi.humidifier.ca1",
      "updateInterval": 30,
      "disabled": false,
      "ledBulb": {
        "enabled": true,
        "name": "Humidifier LED"
      },
      "buzzerSwitch": {
        "enabled": true,
        "name": "Humidifier Buzzer"
      },
      "temperatureSensor": {
        "enabled": true,
        "name": "Humidifier Temperature"
      },
      "humiditySensor": {
        "enabled": true,
        "name": "Humidifier Humidity"
      }
    }
  ]
```

I also tried against `zhimi.humidifier.cb1` for my evaporative humidifier

**Comment by iShift** [comment]
I have cb1 and same error after update...

```
Jan 30 10:41:39 raspberrypi2 homebridge[1867]:     at UDP.onMessage (dgram.js:921:8)
Jan 30 10:41:39 raspberrypi2 homebridge[1867]:     at Socket.emit (events.js:314:20)
Jan 30 10:41:39 raspberrypi2 homebridge[1867]:     at Socket.onMessage (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/socket.ts:118:26)
Jan 30 10:41:39 raspberrypi2 homebridge[1867]:     at socket.send.responseBuffer.responseBuffer (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/device
Jan 30 10:41:39 raspberrypi2 homebridge[1867]:     at Function.fromBuffer (/usr/lib/node_modules/homebridge-mi-humidifier/node_modules/miio-api/src/packet.ts:65:13)
Jan 30 10:41:39 raspberrypi2 homebridge[1867]: [1/30/2021, 10:41:39] Error: Invalid packet size, expected 192 got 32
```

**Comment by russtone** [comment]
Could you please collect debug logs? You can do it by running homebridge like this:

```
DEBUG=miio-api* homebridge -D
```

**Comment by coneybeare** [comment]
````
DEBUG=miio-api* hoobs -d
HOOBS listening on port 80.
/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs bridge -u /home/hoobs/.hoobs/etc -p /home/hoobs/.hoobs/node_modules -r -d
Loaded plugin 'homebridge-bond'
[1/31/2021, 8:33:24 AM] Registering platform 'homebridge-bond.Bond'
Loaded plugin 'homebridge-eufy-robovac'
[1/31/2021, 8:33:24 AM] Registering accessory 'homebridge-eufy-robovac.Eufy RoboVac'
Loaded plugin 'homebridge-homeconnect'
[1/31/2021, 8:33:25 AM] Registering platform 'homebridge-homeconnect.HomeConnect'
Loaded plugin 'homebridge-lg-airco'
[1/31/2021, 8:33:25 AM] Registering accessory 'homebridge-lg-airco.LgAirCooler'
Loaded plugin 'homebridge-lg-thinq-ac'
[1/31/2021, 8:33:25 AM] Registering platform 'homebridge-lg-thinq-ac.LgThinqAirConditioner'
Loaded plugin 'homebridge-mi-humidifier'
[1/31/2021, 8:33:25 AM] Registering platform 'homebridge-mi-humidifier.MiHumidifier'
Loaded plugin 'homebridge-plex-webhooks'
[1/31/2021, 8:33:26 AM] Registering platform 'homebridge-plex-webhooks.PlexWebhooks'
Loading 5 platforms...
[LgThinqAirConditioner] Initializing LgThinqAirConditioner platform...
[LgThinqAirConditioner] Finished initializing platform: undefined
[HomeConnect] Initializing HomeConnect platform...
[HomeConnect] new HomeConnectPlatform
[Bond] Initializing Bond platform...
[Bond] Config: {
  "platform": "Bond",
  "plugin_map": {
    "plugin_name": "homebridge-bond"
  },
  "include_dimmer": false,
  "include_toggle_state": true,
  "fan_speed_values": false,
  "bonds": [
    {
      "ip_address": "[REDACTED]",
      "token": "[REDACTED]"
    }
  ]
}
[Plex Webhooks Platform] Initializing PlexWebhooks platform...
[MiHumidifier] Initializing MiHumidifier platform...
Loading 2 accessories...
[HVAC] Initializing LgAirCooler accessory...
Accessory refresh triggered
[Vacuum Cleaner] Initializing Eufy RoboVac accessory...
Looking for device...
[Vacuum Cleaner] Vacuum Cleaner finished initializing!
Accessory refresh triggered
[LgThinqAirConditioner] Restoring accessory from cache: Master Bedroom
[LgThinqAirConditioner] TargetHeaterCoolerStateCharacteristic: Warning: Your model may support a "drying" or "dehumidification" mode. This is NOT natively supported by Homekit, and using it may show errors in Homebridge or cause temporary instability.
[LgThinqAirConditioner] Not logged in; skipping updateCharacteristics()
[LgThinqAirConditioner] Starting refresh interval (set to 1 minutes)
[LgThinqAirConditioner] Not logged in; skipping renewMonitoring()
[LgThinqAirConditioner] Restoring accessory from cache: Living Room
[LgThinqAirConditioner] TargetHeaterCoolerStateCharacteristic: Warning: Your model may support a "drying" or "dehumidification" mode. This is NOT natively supported by Homekit, and using it may show errors in Homebridge or cause temporary instability.
[LgThinqAirConditioner] Not logged in; skipping updateCharacteristics()
[LgThinqAirConditioner] Starting refresh interval (set to 1 minutes)
[LgThinqAirConditioner] Not logged in; skipping renewMonitoring()
[LgThinqAirConditioner] Executed didFinishLaunching callback
[HomeConnect] Restored 2 cached accessories
[Bond] Request ([REDACTED]) [get http://[REDACTED]/v2/devices]
[Bond] Request ([REDACTED]) [get http://[REDACTED]/v2/sys/version]
[Plex Webhooks Platform] Found 2 accessories in config:
[Plex Webhooks Platform] • Plex Movies
[Plex Webhooks Platform] • Plex TV
[Plex Webhooks Platform] Updating accessory [Plex Movies] ([REDACTED])
[Plex Webhooks Platform] Updating accessory [Plex TV] ([REDACTED])
api_launched
Bridge is running on port [REDACTED].
Setup URI: X-HM://[REDACTED]
Bridge started: Sun Jan 31 2021 08:33:26 GMT-0700 (Mountain Standard Time)
[Plex Webhooks Platform] Server is listening at http://[REDACTED]
/home/hoobs/.hoobs/etc/wideq_state.json
2021-01-31T15:33:26.806Z miio-api:device:ox03hb8w -> {
id: [REDACTED],
method: 'get_prop',
params: [
'power',      'limit_hum',
'child_lock', 'humidity',
'led_b',      'buzzer',
'mode',       'depth',
'dry',        'temp_dec'
]
}
2021-01-31T15:33:26.814Z miio-api:device:ox03hb8w ->
0000    21 31 00 b0 00 00 00 00 07 ea 8d e3 00 02 88 9e
0010    88 ad 0f ed 6a d7 9f 0c 85 1c a9 3a 6c 6b f6 ad
0020    b6 5b c4 05 7e 2e e2 9e 3e 36 c1 27 dd 41 3b 83
0030    a8 b6 ce 2f 54 6b de ed 07 cf b4 fb c6 ea 0d 74
0040    79 99 a3 84 eb 1d d3 3c 78 13 d9 e4 c8 17 ca e0
0050    3d fb 27 04 88 71 6c 83 ec c2 05 62 0f 99 d7 c1
0060    94 be 74 69 c5 eb e1 29 d2 47 72 8f f6 e9 1d 22
0070    a3 ae 6c 4a 31 d8 ad bd f9 e0 84 cc 05 eb ec 58
0080    8d b3 27 5c 0d 4a 77 00 d7 9e 74 c1 d0 04 9e 6c
0090    a9 3e 4e 2d a4 dc 5b 25 15 28 0b c0 b6 55 33 7f
00a0    18 35 a0 69 d3 4c 6b 0d 14 55 08 84 bb bd 34 e6
Error: Invalid packet size, expected 176 got 32
    at Function.fromBuffer (/home/hoobs/.hoobs/node_modules/miio-api/dist/packet.js:30:19)
    at socket.send.responseBuffer.responseBuffer (/home/hoobs/.hoobs/node_modules/miio-api/dist/device.js:148:57)
    at Socket.onMessage (/home/hoobs/.hoobs/node_modules/miio-api/dist/socket.js:101:32)
    at Socket.emit (events.js:314:20)
    at UDP.onMessage [as onmessage] (dgram.js:921:8)
Got SIGTERM, shutting down Bridge...
[Bond] Response (185dd644f3adc000) [get http://[REDACTED]/v2/devices] - {"_":"[REDACTED]","[REDACTED]":{"_":"[REDACTED]"},"[REDACTED]":{"_":"[REDACTED]"}}
[HomeConnect] Refreshing access token in 80049 seconds
[HomeConnect] Starting events stream for all appliances
[HomeConnect] Home Connect request #1: STREAM https://api.home-connect.com/api/homeappliances/events
[HomeConnect] Home Connect request #2: GET https://api.home-connect.com/api/homeappliances
[Bond] Response ([REDACTED]) [get http://[REDACTED]/v2/sys/version] - {"target":"zermatt","fw_ver":"v2.15.8","fw_date":"Wed Nov 11 15:50:17 UTC 2020","uptime_s":[REDACTED],"make":"Olibra","model":"BD-1000","branding_profile":"OLIBRA_BD1000","bondid":"[REDACTED]","upgrade_http":true,"api":2,"_":"[REDACTED]"}
[Bond]
****** Bond Info *******
 bondId: [REDACTED]
 FW: v2.15.8
 API: v2
 Make: BD-1000
 Model: BD-1000
************************
[Bond] 2 cached accessories were loaded
[Bond] Getting devices for this Bond ([REDACTED])...
[Bond] 2 devices were found on this Bond ([REDACTED]).
[Bond] No new devices to add for this Bond ([REDACTED]).
[Bond] UDP message sent to [REDACTED]
[LgThinqAirConditioner] Already logged into ThinQ
[LgThinqAirConditioner] refreshAuth()
[Bond] Configuring Accessory: Kids Room Ceiling fan
[Bond] [Ceiling fan] actions: TurnOff,ToggleDirection,IncreaseSpeed,DecreaseSpeed,ToggleLight,Stop,TogglePower,TurnOn,SetSpeed,SetDirection,TurnLightOn,TurnLightOff
[Bond] Request ([REDACTED]) [get http://[REDACTED]/v2/devices/[REDACTED]/state]
[Bond] Configuring Accessory: Living Room Kichler Fan
[Bond] [Kichler Fan] actions: SetSpeed,ToggleDirection,ToggleLight,TurnOff,Stop,TogglePower,TurnOn,IncreaseSpeed,DecreaseSpeed,SetDirection,TurnLightOn,TurnLightOff
[Bond] Request ([REDACTED]) [get http://[REDACTED]/v2/devices/[REDACTED]/state]
[Bond] UDP Message received from [REDACTED] - {"B":"[REDACTED]"}
2021-01-31 08:33:27 DEBUG [wideq.example] State file found '/home/hoobs/.hoobs/etc/wideq_state.json'
2021-01-31 08:33:27 DEBUG [wideq.example] State file found '/home/hoobs/.hoobs/etc/wideq_state.json'
[Bond] Response ([REDACTED]) [get http://[REDACTED]/v2/devices/[REDACTED]/state] - {"power":1,"speed":0,"direction":1,"light":0,"_":"[REDACTED]"}
[Bond] Response ([REDACTED]) [get http://[REDACTED]/v2/devices/[REDACTED]/state] - {"power":0,"speed":2,"direction":-1,"light":1,"_":"[REDACTED]"}
2021-01-31 08:33:27 DEBUG [wideq.example] Wrote state file '/home/hoobs/.hoobs/etc/wideq_state.json'
2021-01-31 08:33:27 DEBUG [wideq.example] Wrote state file '/home/hoobs/.hoobs/etc/wideq_state.json'
[HomeConnect] Started events stream for all appliances
[HomeConnect] Home Connect request #2: OK +1132ms
[HomeConnect] Found 2 appliances
[HomeConnect] Scheduling configuration schema write
[HomeConnect] Connecting accessory 'Washing machine'
[HomeConnect] [Washing machine] Bosch Washer (E-Nr: [REDACTED]/20)
[HomeConnect] Connecting accessory 'Dryer'
[HomeConnect] [Dryer] Bosch Dryer (E-Nr: [REDACTED]/02)
[HomeConnect] [Washing machine] Cache loaded (18 entries)
[HomeConnect] [Washing machine] Cache 'Appliance power' [en-US, updated 168347 seconds ago] is too old
[HomeConnect] [Washing machine] Restored details of 7 programs
[HomeConnect] [Dryer] Cache loaded (26 entries)
[HomeConnect] [Dryer] Cache 'Appliance power' [en-US, updated 168347 seconds ago] is too old
[HomeConnect] [Dryer] Restored details of 11 programs
Error: find() timed out. Is the device powered on and the ID or IP correct?
at /home/hoobs/.hoobs/node_modules/tuyapi/index.js:622:13
at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/p-timeout/index.js:25:13)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
Connecting...
Robovac Error {}
Disconnected!
[LgThinqAirConditioner] dashboardResponse {
  resultCode: '0000',
  result: {
    langPackCommonVer: '93.5',
    langPackCommonUri: 'https://objectcontent.lgthinq.com/[REDACTED]?hdnts=exp=[REDACTED]~hmac=[REDACTED]',
    item: [ [Object], [Object], [Object] ],
    group: []
  }
}
[LgThinqAirConditioner] Discover found 3 total devices
[LgThinqAirConditioner] "Dining Room" (model [REDACTED]) uses the thinq1 platform, which is not supported. Please see https://github.com/sman591/homebridge-lg-thinq-ac/issues/4 for updates.
[LgThinqAirConditioner] Existing accessory: Master Bedroom
[LgThinqAirConditioner] Existing accessory: Living Room
shutdown
^C[HOOBS] Stopping server.
hoobs@hoobs:~ $
````

I included the entire logs, redacted, but the shutdown is definitely coming from `homebridge-mi-humidifier`, as when I remove the devices and/or the package, there are no issues. Hope this helps

**Comment by russtone** [comment]
It seems that your device token is invalid. Could you please check the token using [miiocli](https://github.com/rytilahti/python-miio) utility?
You can do it using the following commands:
```
pip3 install python-miio
miiocli device --ip <ip> --token <token> info
```

**Comment by coneybeare** [comment]
Sure it is invalid, but that is part of the problem. Resetting, discovering the new token using `miso discover`, configuring wifi, the checking still yields this error, after the most recent update.

````
$ miio discover
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: [REDACTED]
Model info: zhimi.humidifier.cb1
Address: 192.168.1.1
Token: 1f4b9444e769b2400968f6b86e074250 via auto-token
Support: At least generic

^C
$ miio configure 192.168.1.1 --ssid <SSID> --passwd <PWD>
 INFO  Attempting to configure 192.168.1.1

 ERROR  Encountered an error while updating wireless

Error was:
Failed updating wireless
$ miio discover
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 132812259
Model info: Unknown
Address: [REDACTED]
Token: ???
Support: Unknown

^C
$ miiocli device --ip <IP> --token 1f4b9444e769b2400968f6b86e074250 info
Error: Got checksum error which indicates use of an invalid token. Please check your token!
````

The configure error was fake news, as the humidifier is connected to my wifi. 

I also attempted to change the token manually without success.
```
miio tokens update <IP> --token <TOKEN_AS_HEX>
 INFO  Updating token for <IP>

 INFO  Connected to miio:[REDACTED]  - trying to change token

 ERROR  Could not update token, double-check the given token
```

Perhaps the update changed the internal API in some way?

**Comment by russtone** [comment]
As I know, new versions of humidifiers firmware do not allow to obtain token using `miio discover` comand. It is more reliable to use methods described here: https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md

**Comment by coneybeare** [comment]
> As I know, new versions of humidifiers firmware do not allow to obtain token using `miio discover` comand. It is more reliable to use methods described here: https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md

...but it **is** discovering the token as you can see from the output above. Do you think the humidifier is changing the token after wifi configuration?

None-the-less, handling the errors by putting a catch statement around your code would allow installation the plugin without having it crash homebridge on this type of error. Could you update that while I figure out the token issue, if there is one?

**Comment by russtone** [comment]
> ...but it **is** discovering the token as you can see from the output above. Do you think the humidifier is changing the token after wifi configuration?

Yes, some users already mentioned this: https://github.com/russtone/homebridge-mi-humidifier/issues/50#issuecomment-751746227

> None-the-less, handling the errors by putting a catch statement around your code would allow installation the plugin without having it crash homebridge on this type of error. Could you update that while I figure out the token issue, if there is one?

Yes, I will fix this soon

**Comment by coneybeare** [comment]
I used the sqlite method from the iOS backup. The token reported is now 96 chars

**Comment by coneybeare** [comment]
getting the token via the iOS backup finally worked for me. Thanks for the assistance
