### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by phenix13** [russtone/homebridge-mi-humidifier#8]
when set the speed between 1% and 30% ，the device will display "No response".

setRotationSpeed { Error: device_poweroff
    at Object.reject (/home/pi/hbs/humidifier/plugin/miio/lib/device.js:217:13)
    at Device._onMessage (/home/pi/hbs/humidifier/plugin/miio/lib/device.js:108:8)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8) code: -6011 }

Your plugin work well , TKS

**Comment by russtone** [comment]
There shouldn't be such problem in the new version, so I am closing this for now.
